#!/usr/bin/perl -w

#$linha = <STDIN>;
#@valores = split $linha;

print"p cnf 729 porra\n";

our $cont = 1;

#criando matriz com numeros de 1 a 729
for (my $i = 0; $i < 9; $i++) 
{
  for(my $j = 0; $j< 9; $j++)
  {
    for(my $k = 0; $k < 9; $k++)
    {
      $matriz[$i][$j][$k] = $cont++; 
    }
  }
}
#print"OU dos elementos dos vetores pendurados\n";
#OU's dos vetores pendurados ISSO É UM FATOOOOOOOOOOOOOOOOOOOOO!! uma casa tem de ter algum valor
for (my $i = 0; $i < 9; $i++) 
{
  for(my $j = 0; $j< 9; $j++)
  {
    for(my $k = 0; $k < 9; $k++)
    {
      print "$matriz[$i][$j][$k] ";
    }
    print "0\n";
  }
}
#print"2 a 2 elementos dos vetores pendurados\n\n\n\n\n";
#2 a 2 elementos dos vetores pendurados ISSO É UM FATOOOOOOOOO!! e apenas só um valor

for(my $i = 0; $i < 9; $i++) 
{
  for(my $j = 0; $j< 9; $j++)
  {
    for(my $k = 0; $k < 9; $k++)
    {
      for(my $l = $k+1; $l < 9; $l++)
      {
        print "-$matriz[$i][$j][$k] -$matriz[$i][$j][$l] 0\n";
      }
    }
  }
}
#print"OU de linhas\n\n\n\n\n";
#varia colunas primeiro, depois valores e por ultimo linhas(fazendo os OUs aqui)(111 ou 121 ... 191 112 ... 192)#parece certo
for (my $i = 0; $i < 9; $i++) 
{
  for(my $k = 0; $k< 9; $k++)
  {
    for(my $j = 0; $j < 9; $j++)
    {
      print "$matriz[$i][$j][$k] ";
    }
    print "0\n";
  }
  #print "0\n";
}
#print"2 a 2 elementos das linhas\n\n\n\n\n";
#2 a 2 elementos linhas#################################será?###parece certo
for (my $i = 0; $i < 9; $i++) 
{
  for(my $k = 0; $k< 9; $k++)
  {
    for(my $j = 0; $j < 9; $j++)
    {
      for(my $l = $j+1; $l < 9; $l++)
      {
        print "-$matriz[$i][$j][$k] -$matriz[$i][$l][$k] 0\n";
      }
    }
  }
}
#print"OU de colunas\n\n\n\n\n";
#varia linhas primeiro, depois valores e por ultimo colunas(fazendo os OUs aqui)(111 ou 211 ou ... ou 911 ... 112 ... 912)parece certooooooo
for (my $j = 0; $j < 9; $j++) 
{
  for(my $k = 0; $k< 9; $k++)
  {
    for(my $i = 0; $i < 9; $i++)
    {
      print "$matriz[$i][$j][$k] ";
    }
    print "0\n";
  }
  print "\n";
}
#print"2 a 2 elementos das colunas\n\n\n\n\n";
#2 a 2 elementos coluna#################################será?parece certo
for (my $j = 0; $j < 9; $j++) 
{
  for(my $k = 0; $k< 9; $k++)
  {
    for(my $i = 0; $i < 9; $i++)
    {
      for(my $l = $i+1; $l < 9; $l++)
      {
        print "-$matriz[$i][$j][$k] -$matriz[$l][$j][$k] 0\n";
      }
    }
  }
}
#OU mini gridSERAAAAAAAAAAAA????????????
#for (my $i = 0; $i < 9; $i++) 
#{
  #for(my $j = 0; $j< 9; $j++)
  my $i = 0;
  my $j = 0;
  while(1)
  {
   for(my $m = 0; $m < 9; $m++)
    {
      for(my $l = i; $l < $i+3; $l++)
      {
        for(my $k = j; $k < $j+3; $k++)
        {
          print "$matriz[$l][$k][$m] ";
        }
      }
    print "0\n";
    $j += 3;
    if($j > 8){$i += 3;}
    if($j > 8){last;}
    }
  }
#}

#2 a 2 mini gridNAO TA FEITO AINDA
#for (my $i = 0; $i < 9; $i++) 
#{
my $i = 0;
  my $j = 0;
  while(1)
  {
   for(my $m = 0; $m < 9; $m++)
    {
      for(my $l = i; $l < $i+3; $l++)
      {
        for(my $k = j; $k < $j+3; $k++)
        {
          for(my $n = j; $k < $j+3; $n++)
          {
            for(my $o = j; $k < $j+3; $o++)
            {
              print "$matriz[$l][$k][$m] ";
            }
          }
        }
      }
    print "0\n";
    $j += 3;
    if($j > 8){$i += 3;}
    if($j > 8){last;}
    }
  }
#}


